# Site wide variables
title: Aberystwyth Live Action Gaming Society

navigation:
- text: About
  url: /
- text: Rules
  url: /rules
- text: How to play
  url: /rules/howtoplay
- text: Committee
  url: /committee
